### PR TITLE
Take 2: Adding fontmake and fontbakery automation for building TTFs and running quality-assurance checks frequently.

### PR DESCRIPTION
**Pull request by felipesanches**
(issue #7)

### CODE REVIEW

**Comment by felipesanches** [comment]
I decided to open a new pull request working on a new branch and manually picking the commits form the old one to review them and make them compatible with the work being done at master branch

**Comment by marcologous** [comment]
@felipesanches : the only error flagged is the underline thickness?

**Comment by felipesanches** [comment]
hey! Great to see that you're active right now. I am also adding one more commit to this branch to add the METADATA.pb file.

**Comment by felipesanches** [comment]
it will take me maybe 10 or 15 more minutes before I do so, though. I want to make sure it is properly setup before pushing.

**Comment by marcologous** [comment]
There was an error with fontbakery? Something about accessing the namecheck.fontdata.com website?

**Comment by felipesanches** [comment]
yeah. But we know that the "Hanken Grotesk" name is a new one, so no worries. I will add a commit disabling that check.

**Comment by marcologous** [comment]
> yeah. But we know that the "Hanken Grotesk" name is a new one, so no worries. I will add a commit disabling that check.

Great!

**Comment by felipesanches** [comment]
@marcologous, we still have a few FAILs but I think it is cool to merge this PR now so that we at least have the Travis CI setup in place. We will open more PRs later to address these other failing checks.

**Pull request merged**
