### PR TITLE
Adding fontmake and fontbakery automation

### PR DESCRIPTION
**Pull request by felipesanches**
for building TTFs and running quality-assurance checks frequently.
(issue #7)

### CODE REVIEW

**Comment by marcologous** [comment]
I see that the Travis build failed

**Comment by felipesanches** [comment]
ok, let's take care of that :-)

**Comment by felipesanches** [comment]
The glyphs source files with space characters in the filename caused the `fontmake` command to fail. I could add quotes around the command, but I think I'd rather prefer to rename the files to remove the space char.

I will also further tweak the build script to not run the FB checks that are currently resulting in FAIL or WARN and I will open individual issues for each of them so that we can later fix them one by one.

I'll let you know when this is good to merge.

**Comment by felipesanches** [comment]
I'm not sure what exactly this means, but maybe you can figure it out, @marcologous 
Here's a portion of the build log in which we see some warnings:
Screenshot from 2020-06-15 19-03-00

There are also lots of these:
Screenshot from 2020-06-15 19-05-14

And then these warnings about a clash between instance coordinates:
Screenshot from 2020-06-15 19-06-55

Which is probably what caused the final error which results in the TTFs not being properly generated:
Screenshot from 2020-06-15 19-08-59

Then the same thing happens with the `HankenGrotesk.glyphs` file.


The full build log with these warnings and errors is available at https://travis-ci.org/github/marcologous/hanken-grotesk/builds/698715099

**Comment by marcologous** [comment]
I think I have an idea. Let me fix those!

**Comment by felipesanches** [comment]
ok, cool! ;-)

**Comment by marcologous** [comment]
I have been pushing some updates to your pr/8 branch. Is that ok or shall I commit stuff only to my branch?

**Comment by marcologous** [comment]
> ok, cool! ;-)

**Comment by marcologous** [comment]
I am still addressing some of the issues and am working on the source files. Is it possible to run whatever we have now or shall we just wait till the source files have been edited?

**Comment by marcologous** [comment]
Regarding Instance User-space location warning: Here's an example -> https://github.com/Omnibus-Type/Saira/issues/9

**Pull request closed without merging**
